### ISSUE TITLE
Docker image?

### ISSUE THREAD

**Issue by metasoarous** [HCADatalab/IClojure#7]
Any chance of getting a docker image with up to date Jupyter & IClojure installed? This was super helpful for me getting my `(+ oz clojupyter)` plugin working, and I suspect would be helpful for others looking to get going with IClojure quickly.

Thanks for all your work.

**Comment by cgrand** [comment]
Here you go https://hub.docker.com/r/cgrand/iclojure

**Comment by metasoarous** [comment]
Amazing! Thank you!
