### ISSUE TITLE
Missing feature: autocomplete

### ISSUE THREAD

**Issue by keesterbrugge** [HCADatalab/IClojure#9]
Hi @cgrand,

Thanks for fixing the issue's so quick, this tool is getting better day by day!

I miss autocomplete a lot though, clojupyter provides it out of the box, see image. Is there a way for me to enable it?
![screenshot 2019-01-25 at 11 14 38](https://user-images.githubusercontent.com/6086439/51739982-21270f00-2093-11e9-87e4-18590e214e68.png)

**Comment by cgrand** [comment]
@keesterbrugge autocomplete is back, sorry for the inconvenience
